create database universe;
\c universe;
create table galaxy;
create table galaxy();
create table star();
create table planet();
create table moon();
create table multiverse();
alter table galaxy add column galaxy_id SERIAL PRIMARY KEY;
alter table star add column star_id serial primary key;
alter table planet add column planet_id serial primary key;
alter table moon add column moon_id serial primary key;
alter table galaxy add column name varchar(50);
alter table star add column name varchar(50);
alter table planet add column name varchar(50);
alter table moon add column name varchar(50);
alter table galaxy add column int1 serial;
alter table galaxy add column int2 serial;
alter table star add column int1 serial;
alter table star add column int2 serial;
alter table planet add column int1 serial;
alter table planet add column int2 serial;
alter table moon add column int1 serial;
alter table moon add column int2 serial;
alter table galaxy add column note text;
alter table galaxy add column numer numeric(2,2);
alter table moon add column bool boolean;
alter table planet add column bool boolean;
alter table star add column galaxy_id serial;
alter table star add foreign key(galaxy_id) references galaxy(galaxy_id);
alter table multiverse add column name varchar(100);
alter table multiverse add multiverse_id serial;
alter table multiverse drop multiverse_id;
alter table multiverse add column multiverse_id serial primary key;
alter table planet add column star_id serial;
alter table planet add foreign key(star_id) references star(star_id);
alter table moon add planet_id serial;
alter table moon add foreign key(planet_id) references planet(planet_id);
alter table galaxy alter column name set not null;
alter table galaxy add constraint unique_name unique(name);
alter table star alter column name set not null;
alter table planet alter column name set not null;
alter table moon alter column name set not null;
alter table star add constraint unique_name1 unique(name);
alter table planet add constraint unique_name2 unique(name);
alter table moon add constraint unique_name3 unique(name);
insert into galaxy(name, int1,int2) values('a',12,21);
insert into star(name,int1,int2,galaxy_id) values ('aa',10,101,1);
insert into galaxy(name, int1,int2) values('b',121,211);   
insert into galaxy(name, int1,int2) values('c',122,212);
insert into galaxy(name, int1,int2) values('d',123,213);
insert into galaxy(name, int1,int2) values('e',124,214);
insert into galaxy(name, int1,int2) values('f',125,215);
insert into galaxy(name, int1,int2) values('g',126,216);
insert into star(name,int1,int2,galaxy_id) values ('bb',101,102,2);
insert into star(name,int1,int2,galaxy_id) values ('cc',102,103,3);
insert into star(name,int1,int2,galaxy_id) values ('dd',104,104,4);
insert into star(name,int1,int2,galaxy_id) values ('ee',103,105,5);
insert into star(name,int1,int2,galaxy_id) values ('ff',104,106,6);
insert into planet(name,int1,int2,star_id) values('aaa',01,02,1);
insert into planet(name,int1,int2,star_id) values('aab',02,02,1);
insert into planet(name,int1,int2,star_id) values('aac',03,02,1);
insert into planet(name,int1,int2,star_id) values('abb',03,02,2);
insert into planet(name,int1,int2,star_id) values('abc',03,03,2);
insert into planet(name,int1,int2,star_id) values('abd',04,03,3);
insert into planet(name,int1,int2,star_id) values('baa',04,04,3);
insert into planet(name,int1,int2,star_id) values('bab',04,54,4);
insert into planet(name,int1,int2,star_id) values('bac',04,54,4);
insert into planet(name,int1,int2,star_id) values('bba',04,54,5);
insert into planet(name,int1,int2,star_id) values('bbc',04,06,5);
insert into planet(name,int1,int2,star_id) values('caa',04,06,6);
insert into planet(name,int1,int2,star_id) values('cab',14,16,6);
insert into planet(name,int1,int2,star_id) values('cac',07,06,6);
insert into moon(name,int1,int2,planet_id) values ('aaaa',01,20,1);
insert into moon(name,int1,int2,planet_id) values ('aaab',02,19,1);
insert into moon(name,int1,int2,planet_id) values ('aaac',03,18,1);
insert into moon(name,int1,int2,planet_id) values ('aaad',04,17,1);
insert into moon(name,int1,int2,planet_id) values ('aaae',05,16,1);
insert into moon(name,int1,int2,planet_id) values ('aaba',06,15,2);
insert into moon(name,int1,int2,planet_id) values ('aabb',07,14,2);
insert into moon(name,int1,int2,planet_id) values ('aabc',08,13,2);
insert into moon(name,int1,int2,planet_id) values ('aabd',09,12,2);
insert into moon(name,int1,int2,planet_id) values ('aabe',10,11,2);
insert into moon(name,int1,int2,planet_id) values ('aaca',11,10,3);
insert into moon(name,int1,int2,planet_id) values ('aacb',12,09,3);
insert into moon(name,int1,int2,planet_id) values ('aacc',13,08,3);
insert into moon(name,int1,int2,planet_id) values ('aacd',14,07,4);
insert into moon(name,int1,int2,planet_id) values ('aace',15,06,4);
insert into moon(name,int1,int2,planet_id) values ('aada',16,05,5);
insert into moon(name,int1,int2,planet_id) values ('aadb',17,04,5);
insert into moon(name,int1,int2,planet_id) values ('aade',18,03,5);
insert into moon(name,int1,int2,planet_id) values ('aadc',19,02,5);
insert into moon(name,int1,int2,planet_id) values ('aadd',10,01,5);
insert into moon(name,int1,int2,planet_id) values ('abae',20,00,5);
insert into multiverse(name) values('q');
insert into multiverse(name) values('e');
insert into multiverse(name) values('w');
insert into multiverse(name) values('r');
alter table multiverse add column note varchar(100);
alter table multiverse alter column name set not null;
alter table multiverse add constraint unique_name4 unique(name);
